# A test which runs the e2e cypress tests on the online hosted version of the PyMedPhys app
# which is at https://app.pymedphys.com. This test is on a schedule so that there is a
# track record of the application running with time.

# It does not make sense to run it on PR or push as any particular PR or push won't yet actually
# be live on the web-app. This test is independent of any given branch.

name: OnlineApp

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Heat Online App
        run: |
          curl -s -o /dev/null https://app.pymedphys.com -w ''%{http_code}''

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Cypress
        working-directory: lib/pymedphys/tests/e2e
        run: |
          yarn

      - name: Wait for Online App to Start
        run: |
          while [[ "$(curl -s -o /dev/null https://app.pymedphys.com -w ''%{http_code}'')" != "200" ]]; do sleep 1; done

      - name: Run Cypress
        working-directory: lib/pymedphys/tests/e2e
        run: |
          export CYPRESS_PYMEDPHYS_GUI_URL="https://app.pymedphys.com"
          yarn cypress run --spec cypress/integration/streamlit/metersetmap.spec.js
